version: 2

updates:
- package-ecosystem: gomod
  directory: "/"
  reviewers: ["bringg/devops"]
  schedule:
    interval: weekly
    day: saturday

- package-ecosystem: github-actions
  directory: "/"
  reviewers: ["bringg/devops"]
  schedule:
    interval: weekly
    day: saturday
