name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Install tools
        run: make tools.golangci-lint

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make unit
